In [1]:
import numpy as np

In [10]:
%config Completer.use_jedi = False #this is command used for enable autocompletion in jupyt notebook

In [3]:
l=[3,4,5,"lalit"]

In [4]:
type(l)

list

In [5]:
#conversion of list into n-d arrray

In [6]:
np.array(l)

array(['3', '4', '5', 'lalit'], dtype='<U11')

In [7]:
type(np.array(l))
#n-dimensional array

numpy.ndarray

In [8]:
#two square bracket means 2-d array
np.array([[1,2,3]])

array([[1, 2, 3]])

In [9]:
np.array([[1,2,3,4]])

array([[1, 2, 3, 4]])

In [10]:
np.array([[1,2,3,4]], ndmin=10)

array([[[[[[[[[[1, 2, 3, 4]]]]]]]]]])

In [11]:
#conversion into matrix 

In [12]:
np.mat([1,2,3,4])

matrix([[1, 2, 3, 4]])

In [13]:
arr = np.array([3,4,5,6,7])

In [14]:
arr

array([3, 4, 5, 6, 7])

In [15]:
arr[0]

3

In [16]:
arr[0:3]

array([3, 4, 5])

In [17]:
arr[0:3:2]

array([3, 5])

In [18]:
#2-d array bcz there 2 open and 2 closed bracket
arr=np.array([[1,2],[3,4] , [4,5]])

In [42]:
arr

array([[1, 2],
       [3, 4],
       [4, 5]])

In [43]:
arr[0]

array([1, 2])

In [44]:
arr[1]

array([3, 4])

In [45]:
arr[1][0]

3

In [46]:
arr[1][1]

4

In [48]:
arr[2][1]

5

In [54]:
np.asarray([3,4,5])

array([3, 4, 5])

In [21]:
#conversion of intiger type to float32/float64

In [22]:
np.asarray([3,4,5],dtype=np.float32)

array([3., 4., 5.], dtype=float32)

In [23]:
np.asanyarray([3,4,5,6,7])

array([3, 4, 5, 6, 7])

In [24]:
np.asanyarray(np.mat([1,2,3,4,5]))

matrix([[1, 2, 3, 4, 5]])

In [25]:
#Generate array from fromfunction
np.fromfunction(lambda i, j :j*i, (3,3),dtype=int)

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

In [36]:
np.fromfunction(lambda i, j:i**2, (3,3),dtype=float)

array([[0., 0., 0.],
       [1., 1., 1.],
       [4., 4., 4.]])

In [37]:
#Generate array from fromfunction
np.fromfunction(lambda i, j :j+i, (3,3),dtype=int)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [38]:
#Generate array from fromfunction
np.fromfunction(lambda i, j, k :j*i, (3,3,2),dtype=int)

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [1, 1],
        [2, 2]],

       [[0, 0],
        [2, 2],
        [4, 4]]])

In [39]:
np.fromfunction(lambda i, j, k :j*i, (3,3,1),dtype=int)

array([[[0],
        [0],
        [0]],

       [[0],
        [1],
        [2]],

       [[0],
        [2],
        [4]]])

In [125]:
np.fromfunction(lambda i, j, k :j*i, (2,3,2),dtype=int)

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [1, 1],
        [2, 2]]])

In [126]:
np.fromfunction(lambda i, j, k :j*i, (3,2,2),dtype=int)

array([[[0, 0],
        [0, 0]],

       [[0, 0],
        [1, 1]],

       [[0, 0],
        [2, 2]]])

In [42]:
np.fromiter()

TypeError: fromiter() missing required argument 'iter' (pos 1)

In [43]:
for i in 5 :
    print(i)

TypeError: 'int' object is not iterable

In [44]:
for i in "lalit":
    pass

In [45]:
for i in "s":
    pass

In [46]:
for i in [2,3,4,5,6]:
    pass

In [47]:
s='lalit'
next(s)

TypeError: 'str' object is not an iterator

In [48]:
s="lalit"

In [130]:
i = iter(s)

In [131]:
s

'lalit'

In [132]:
next(i)

'l'

In [133]:
next(i)

'a'

In [134]:
next(i)

'l'

In [135]:
next(i)

'i'

In [136]:
next(i)

't'

In [137]:
next(i)

StopIteration: 

In [138]:
myfunc()

0


TypeError: 'int' object is not iterable

In [139]:
np.fromfunction(myfunc(),(3,3),dtype=float)

0


TypeError: 'int' object is not iterable

In [140]:
np.fromfunction(lambda i,j,k :i+j+k, (3,3,2),dtype=int)

#shape=(3,3,2) means 3 dimension with 3 rows x 2 columns 

array([[[0, 1],
        [1, 2],
        [2, 3]],

       [[1, 2],
        [2, 3],
        [3, 4]],

       [[2, 3],
        [3, 4],
        [4, 5]]])

In [2]:
range(20)

range(0, 20)

In [3]:
import numpy as np

In [7]:
list(range(2,7))

[2, 3, 4, 5, 6]

In [8]:
list(range(2,7,2))

[2, 4, 6]

In [9]:
list(range(2,7.3))

TypeError: 'float' object cannot be interpreted as an integer

In [11]:
#Possible to generate array of float number by numpy 
np.arange(0,7.3)

array([0., 1., 2., 3., 4., 5., 6., 7.])

In [13]:
#Possible to generate array of float number by numpy 
np.arange(0,20.3,2.5)

array([ 0. ,  2.5,  5. ,  7.5, 10. , 12.5, 15. , 17.5, 20. ])

In [18]:
#create 1 d array of elements from 1 to 6, it create 50 elements bydefault
np.linspace(1,6)

array([1.        , 1.10204082, 1.20408163, 1.30612245, 1.40816327,
       1.51020408, 1.6122449 , 1.71428571, 1.81632653, 1.91836735,
       2.02040816, 2.12244898, 2.2244898 , 2.32653061, 2.42857143,
       2.53061224, 2.63265306, 2.73469388, 2.83673469, 2.93877551,
       3.04081633, 3.14285714, 3.24489796, 3.34693878, 3.44897959,
       3.55102041, 3.65306122, 3.75510204, 3.85714286, 3.95918367,
       4.06122449, 4.16326531, 4.26530612, 4.36734694, 4.46938776,
       4.57142857, 4.67346939, 4.7755102 , 4.87755102, 4.97959184,
       5.08163265, 5.18367347, 5.28571429, 5.3877551 , 5.48979592,
       5.59183673, 5.69387755, 5.79591837, 5.89795918, 6.        ])

In [19]:
np.linspace(1,6,5)

array([1.  , 2.25, 3.5 , 4.75, 6.  ])

In [20]:
np.linspace(1,6,10)

array([1.        , 1.55555556, 2.11111111, 2.66666667, 3.22222222,
       3.77777778, 4.33333333, 4.88888889, 5.44444444, 6.        ])

In [21]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [25]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [26]:
np.zeros((2,4,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [27]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [28]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [29]:
np.ones((2,3))+1

array([[2., 2., 2.],
       [2., 2., 2.]])

In [30]:
np.empty((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [31]:
#create identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [36]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Important Function 

In [38]:
#generate array of ragndom num, 3 rows x 5 columns
np.random.rand(3,5)

array([[0.20250475, 0.2274392 , 0.51704708, 0.08933251, 0.06220241],
       [0.53106942, 0.86722778, 0.99199755, 0.863359  , 0.4535597 ],
       [0.49275277, 0.78023148, 0.75196581, 0.46996506, 0.90733488]])

In [40]:
#3 mat of 5rows x 5 columns
np.random.rand(3,5,5) 

array([[[0.19833136, 0.77347313, 0.86210271, 0.09147409, 0.93976213],
        [0.80925482, 0.69120217, 0.9737753 , 0.8722194 , 0.78964365],
        [0.97921579, 0.39130662, 0.15185972, 0.92103583, 0.54199615],
        [0.83971963, 0.39335572, 0.71600893, 0.33371445, 0.17267426],
        [0.19401893, 0.20693376, 0.16942348, 0.07429868, 0.05863107]],

       [[0.6598634 , 0.85257248, 0.9371328 , 0.01236156, 0.85395896],
        [0.65418158, 0.49025459, 0.65486889, 0.28764694, 0.04725977],
        [0.71549494, 0.94472976, 0.34766619, 0.45294134, 0.58594722],
        [0.26952258, 0.33774672, 0.73472091, 0.87405458, 0.72990527],
        [0.41327338, 0.3280332 , 0.55334052, 0.5145683 , 0.06304259]],

       [[0.98871486, 0.38378828, 0.16763769, 0.34818055, 0.46487524],
        [0.06628305, 0.53086035, 0.51343569, 0.37521882, 0.23534363],
        [0.32351349, 0.70261708, 0.25888939, 0.87464974, 0.1904379 ],
        [0.84748689, 0.26372446, 0.91565494, 0.62549869, 0.61732458],
        [0.96256

In [42]:
    np.random.randn(4,5)

array([[-1.01556922,  1.23705762, -0.30326099,  0.03583376, -1.31654039],
       [ 0.61584315,  0.51772677, -1.55897478, -0.4584479 , -0.90597031],
       [ 0.51527908, -0.82132445, -0.59787399,  0.2406024 , -0.41581609],
       [-0.43799539, -0.23389299,  1.26728937, -0.65005595, -0.04347078]])

In [44]:
np.random.randint(3,10)

7

In [45]:
np.random.randint(3,10,size=10)

array([9, 4, 6, 4, 8, 7, 3, 5, 8, 7])

In [48]:
np.random.randint(2,4,(4,5))

array([[3, 3, 2, 2, 2],
       [3, 3, 2, 3, 3],
       [2, 3, 3, 3, 2],
       [3, 3, 2, 3, 2]])

In [49]:
np.random.randint(10,15,(5,5))

array([[12, 12, 11, 14, 14],
       [12, 12, 10, 10, 12],
       [10, 11, 12, 10, 13],
       [14, 12, 12, 12, 11],
       [10, 10, 11, 12, 14]])

In [71]:
arr=np.random.randint(2,4,(5,5))

In [51]:
arr

array([[2, 3, 3, 3, 3],
       [2, 3, 2, 2, 2],
       [3, 2, 3, 3, 3],
       [2, 3, 3, 3, 3],
       [3, 2, 3, 3, 3]])

In [52]:
arr.shape

(5, 5)

In [74]:
arr.reshape(5,5)

array([[2, 3, 3, 2, 3],
       [3, 2, 3, 3, 3],
       [2, 3, 2, 2, 3],
       [3, 2, 3, 3, 3],
       [2, 3, 3, 2, 3]])

In [75]:
arr

array([[2, 3, 3, 2, 3],
       [3, 2, 3, 3, 3],
       [2, 3, 2, 2, 3],
       [3, 2, 3, 3, 3],
       [2, 3, 3, 2, 3]])

In [77]:
arr.max()

3

In [78]:
#replace an element 
arr[0,1]

3

In [79]:
arr[0,1]=111

In [80]:
arr

array([[  2, 111,   3,   2,   3],
       [  3,   2,   3,   3,   3],
       [  2,   3,   2,   2,   3],
       [  3,   2,   3,   3,   3],
       [  2,   3,   3,   2,   3]])

In [81]:
#matrix
mat1=np.random.randint(5,7,(3,3))

In [82]:
mat1

array([[5, 6, 6],
       [6, 5, 5],
       [6, 6, 6]])

In [85]:
mat2=np.random.randint(8,10,(3,3))

In [86]:
mat2

array([[8, 9, 9],
       [9, 8, 8],
       [8, 9, 9]])

In [87]:
#Elementwise multipication 
mat1*mat2

array([[40, 54, 54],
       [54, 40, 40],
       [48, 54, 54]])

In [88]:
#Matrix multipication 
mat1@mat2

array([[142, 147, 147],
       [133, 139, 139],
       [150, 156, 156]])

In [89]:
arr/0

C:\Users\SANU\Miniconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf]])

In [90]:
#Transpose mat
arr.T

array([[  2,   3,   2,   3,   2],
       [111,   2,   3,   2,   3],
       [  3,   3,   2,   3,   3],
       [  2,   3,   2,   3,   2],
       [  3,   3,   3,   3,   3]])

In [91]:
arr

array([[  2, 111,   3,   2,   3],
       [  3,   2,   3,   3,   3],
       [  2,   3,   2,   2,   3],
       [  3,   2,   3,   3,   3],
       [  2,   3,   3,   2,   3]])

In [92]:
arr**2

array([[    4, 12321,     9,     4,     9],
       [    9,     4,     9,     9,     9],
       [    4,     9,     4,     4,     9],
       [    9,     4,     9,     9,     9],
       [    4,     9,     9,     4,     9]], dtype=int32)

In [97]:
mat1=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [98]:
mat1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [99]:
np.log10(mat1)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125],
       [0.84509804, 0.90308999, 0.95424251]])

In [100]:
np.sqrt(mat1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [101]:
np.pi

3.141592653589793

In [102]:
pwd

'C:\\Users\\SANU'