In [28]:
%config Completer.use_jedi = False #this is command used for enable autocompletion in jupyt notebook

In [29]:
import numpy as np

In [30]:
import pandas as pd

# Write a function so that the columns of the output matrix are powers of the input vector.

In [31]:
def mat(arr):
    mat = np.column_stack([arr**(len(arr)-i-1) for i in range(len(arr))])
    return mat

In [32]:
mat(np.array([1,2,3,4,5]))


array([[  1,   1,   1,   1,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1],
       [625, 125,  25,   5,   1]], dtype=int32)

# 

# The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

In [33]:
x=np.array([1,2,3,4,5]) 

In [34]:
x

array([1, 2, 3, 4, 5])

In [35]:
matrix1 = np.vander(x,len(x),increasing=False)

In [36]:
matrix1

array([[  1,   1,   1,   1,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1],
       [625, 125,  25,   5,   1]])

# Problem Statement 2:
Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
the given sequence is defined as follows:
The moving average sequence has n-k+1 elements as shown below.
The moving averages with k=4 of a ten-value sequence (n=10) is shown below


Question: Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [63]:
def move_avg(s,k):
    sum =0
    t=0
    for i in range(len(s)-k+1):
        for j in range(t,k+t):
            sum=(sum+s[j])
        print("Moving average ","Y",i+1, " ",sum/k)
        sum=0
        t=t+1
    #print(sum)
    

In [65]:
move_avg([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150],3)

Moving average  Y 1   5.0
Moving average  Y 2   4.666666666666667
Moving average  Y 3   5.666666666666667
Moving average  Y 4   6.666666666666667
Moving average  Y 5   9.666666666666666
Moving average  Y 6   28.666666666666668
Moving average  Y 7   49.333333333333336
Moving average  Y 8   72.66666666666667
Moving average  Y 9   84.0
Moving average  Y 10   93.33333333333333
Moving average  Y 11   116.33333333333333
